#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MOTOR_RIGHT_PWM 9
#define MOTOR_RIGHT_DIR 10
#define MOTOR_LEFT_PWM 11
#define MOTOR_LEFT_DIR 12

#define MILLIS_BEFORE_CHANGE 2500
#define TRIGGER_MAX 700
#define MAX_READING 8190

#endif